# Generated by Django 4.1.4 on 2023-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_booking_number_alter_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number',
        ),
    ]
