# Generated by Django 4.1.4 on 2023-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_booking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(null=True, verbose_name=' check in date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(null=True, verbose_name=' check out date'),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_num',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
