# Generated by Django 4.1.4 on 2023-01-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_booking_date_booking_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='reservation_num',
        ),
    ]
